// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.182
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GitScc
{
    static class Vsix
    {
        public const string Id = "GitSccProvider.Microsoft.88d658b3-e361-4e7f-8f4d-9e78f6e4515a";
        public const string Name = "Easy Git Integration Tools";
        public const string Description = "Easy Git Integration Tools (EZ-GIT) is a plug-in that integrates git with Visual Studio.";
        public const string Language = "en-US";
        public const string Version = "1.6.0.0";
        public const string Author = "Jon Zoss";
        public const string Tags = "";
    }
}
